"""schema initial : users, consents, settings, transactions, alerts, alert_responses, outbox, ussd_sessions

Revision ID: b9341f701064
Revises: 
Create Date: 2026-09-20 18:32:42.772458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9341f701064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('telephone_hash', sa.String(length=64), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('desinscrit', sa.Boolean(), nullable=False),
    sa.Column('bloque_jusqu_a', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telephone_hash'), 'users', ['telephone_hash'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('ussd_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('telephone_hash', sa.String(length=64), nullable=False),
    sa.Column('etat', sa.JSON(), nullable=False),
    sa.Column('historique', sa.Text(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ussd_sessions_session_id'), 'ussd_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_ussd_sessions_telephone_hash'), 'ussd_sessions', ['telephone_hash'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consenti', sa.Boolean(), nullable=False),
    sa.Column('version_texte', sa.String(length=16), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('corps', sa.String(length=160), nullable=False),
    sa.Column('canal', sa.String(length=8), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plafond', sa.Integer(), nullable=False),
    sa.Column('plafond_nocturne', sa.Integer(), nullable=False),
    sa.Column('liste_blanche', sa.JSON(), nullable=False),
    sa.Column('canal_prefere', sa.String(length=8), nullable=False),
    sa.Column('langue', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('type_operation', sa.String(length=16), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('destinataire_hash', sa.String(length=64), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('motif', sa.String(length=160), nullable=False),
    sa.Column('latence_ms', sa.Float(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type_operation', sa.String(length=16), nullable=False),
    sa.Column('heure', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=160), nullable=False),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_table('alert_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('reponse', sa.Integer(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_responses')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('transactions')
    op.drop_table('settings')
    op.drop_table('outbox')
    op.drop_table('consents')
    op.drop_index(op.f('ix_ussd_sessions_telephone_hash'), table_name='ussd_sessions')
    op.drop_index(op.f('ix_ussd_sessions_session_id'), table_name='ussd_sessions')
    op.drop_table('ussd_sessions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_telephone_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
